/* TABLE TO HANDLE WEB USER DATA */
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR(255) NOT NULL,
	`password` VARCHAR(32) NOT NULL,
	`email` VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* TABLE TO REPRESENT RPG TYPES (Horror, SciFi, Fantasy, etc) */
DROP TABLE IF EXISTS `GameCategory`;
CREATE TABLE `GameCategory` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* TABLE TO REPRESENT ROLE PLAYING GAMES */
DROP TABLE IF EXISTS `Game`;
CREATE TABLE `Game` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`category_id` INT UNSIGNED NOT NULL REFERENCES `GameCategory`(`id`) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* JOIN TABLE FOR GAMES THAT USERS PLAY */
DROP TABLE IF EXISTS `UserGame`;
CREATE TABLE `UserGame` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`user_id` INT UNSIGNED NOT NULL REFERENCES `User`(`id`) ON DELETE CASCADE,
	`game_id` INT UNSIGNED NOT NULL REFERENCES `Game`(`id`) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

